GET http://localhost:5000/users/logout

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"ocka@ocka.com",
    "password":"12345678910"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"paradise@gmail.com",
    "password":"12345678910"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"aloevera@gmail.com",
    "password":"12345678910"
}

###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "email":"max.mustermann@gmail.com",
    "firstName":"Max",
    "lastName": "Mustermann",
    "city":"Hamburg",
    "password":"12345678910",
    "passwordConfirm":"12345678910",
    "userType":"client"
}

###

GET http://localhost:5000/users/auth

###

POST http://localhost:5000/listings/add-listing
Content-Type: application/json

{
"cafeName": "jane doe",
"listingName": "undefined",
"totalPieces": "10",
"piecePrice": "",
"pickUpDate": "2021-02-24T06:32",
"listingStatus":"active"
}

###

POST http://localhost:5000/cafes/
Content-Type: application/json

{
"city":"Düsseldorf"
}

###
POST http://localhost:5000/cafes/info
Content-Type: application/json

{
"id":"60338921fe5e3c44ccee674b"
}

###
PUT http://localhost:5000/users/update
Content-Type: application/json

{
"userType":"cafe",
"cafeName":"Paradise",
"firstName": "Jane",
"lastName": "Doe",
"city": "Düsseldorf",
"cafeStreet": "Königsallee",
"cafeStreetNr": "92",
"cafeZip": "40212"
}

###

GET http://localhost:5000/users/profile-info

###

PUT http://localhost:5000/listings/checkout
Content-Type: application/json

{
    "pcs":4,
    "listingId": "60339e23ebc07c6a9dec75ca"
}

###

GET http://localhost:5000/listings/cafe

###
POST http://localhost:5000/listings/archive
Content-Type: application/json

{
    "listingID": "603e3a1b6ba690001562ef34",
}

###

GET http://localhost:5000/listings/end-soon


###

GET http://localhost:5000/users/orders

###

GET http://localhost:5000/users/cities