GET http://localhost:5000/users/logout

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"max.mustermann@gmail.com",
    "password":"12345678910"
}

###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "email":"max.mustermann@gmail.com",
    "firstName":"Max",
    "lastName": "Mustermann",
    "city":"Hamburg",
    "password":"12345678910",
    "passwordConfirm":"12345678910",
    "userType":"client"
}

###

GET http://localhost:5000/users/auth

###

POST http://localhost:5000/listings/addlisting
Content-Type: application/json

{
"cafeName": "jane doe",
"listingName": "strawberry cheescake",
"listingTags": "[vegetarian]",
"listingAllergenes": "[dairy]",
"totalPieces": 10,
"piecePrice": 2,
"pickUpDate": "2021-02-21",
"listingStatus":"active"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"ocka@ocka.com",
    "password":"12345678910"
}